_target_: nuplan.planning.training.modeling.models.diffusion_model.DiffusionModel
_convert_: 'all'

# Encoder setup
map_net_scales: 4
num_res_blocks: 3
num_attention_layers: 4
a2a_dist_threshold: 20.0
l2a_dist_threshold: 30.0
num_output_features: 48
feature_dim: 128

# Diffusion setup
sampling_method: 'ddpm' # 'ddpm' or 'ddim'
sampling_stride: 20 # The parameter within DDIM, in the context of DDPM is set to 1

# Parameters for variance schedule
variance_schedule:
  _target_: nuplan.planning.training.modeling.models.diffusion_utils.VarianceSchedule
  _convert_: 'all'
  num_steps: 100
  mode: 'linear'
  beta_1: 1e-4
  beta_T: 5e-2
  cosine_s: 8e-3

# Parameters for dynamics
dynamics: 
  _target_: nuplan.planning.training.modeling.models.diffusion_dynamics.Unicycle # SingleIntegrator or Unicycle
  _convert_: 'all'

# Parameters for sample selector
sample_selector: 
  _target_: nuplan.planning.training.modeling.models.diffusion_utils.SampleSelector
  _convert_: 'all'
  num_samples: 20

# VectorMapFeatureBuilder
vector_map_feature_radius: 50    # [m] The query radius scope relative to the current ego-pose.
vector_map_connection_scales: [1, 2, 3, 4] # Use 4 scale connections which consider 1,2,3,4-hop neighbor lane

# Parameters for past trajectory
past_trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  num_poses: 4      # target past poses
  time_horizon: 2.0  # [s] time horizon of past poses

# Parameters for predicted trajectory
future_trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  num_poses: 16      # target future poses
  time_horizon: 8.0  # [s] time horizon of future poses
